spring:
  application:
      name: cab-driver-service
  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR
  jpa:
    properties:
      hibernate:
           ddl_auto: update
    show-sql: true
    
    
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka
      
server:
  port: 4040